behaviors:
  ZombieBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 512
      num_epoch: 3
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      beta: 5.0e-4
      beta_schedule: constant
      epsilon: 0.2
      lambd: 0.95
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: true
    checkpoint_interval: 1000